Nevstruev Vladislav. First task
fediq/mipt-java-2016 pull request #105
Opened 2016-10-15 16:22 UTC by veschii0nevstrui

У меня всё работает очень странно. Я ничего не понимаю. Но код вроде могу выслать, поэтому высылаю

2016-10-16 12:33 UTC, malchun requested changes
Приведите названи PR к оглашенному на первом семинаре (можете посмотреть у одногруппников). В следующий раз работы с неправильными именами будут игнорироваться.

2016-10-16 12:33 UTC, malchun commented on tasks/01-Calculator.md
> -
Если не секрет - зачем вы удалили задание?

2016-10-16 12:33 UTC, malchun commented on homework-g594-nevstruev/src/main/java/ru/mipt/java2016/homework/g594/nevstruev/task1/MyCalculator.java
> +        if ((last == '+' || last == '-' || last == '*' || last == '/' || last == '.') &&
Эта функция абсолютно нечитабельна. Либо перепишите более очевидным образом, либо добавьте комментарии, объясняющие что тут происходит. Имеющихся точно недостаточно.

2016-10-16 12:33 UTC, malchun commented on homework-g594-nevstruev/src/main/java/ru/mipt/java2016/homework/g594/nevstruev/task1/MyCalculator.java
> +        String ss = s.replaceAll("\n", "").replaceAll(" ", "").replaceAll("\t", "");
Пишите понятные имена, их за вас все-равно подставит IDE.

2016-10-16 12:33 UTC, malchun commented on homework-g594-nevstruev/src/main/java/ru/mipt/java2016/homework/g594/nevstruev/task1/MyCalculator.java
> +            if (!((ch >= '0' && ch <= '9') || ch == '.' || ch == '-')) {
Используйте Character.isDigit.

2016-10-16 21:19 UTC, veschii0nevstrui commented on homework-g594-nevstruev/src/main/java/ru/mipt/java2016/homework/g594/nevstruev/task1/MyCalculator.java
> +        if ((last == '+' || last == '-' || last == '*' || last == '/' || last == '.') &&
Комментарии можно на русском оставлять? От моего английского будет хуже, чем от кода без комментариев.

2016-10-16 21:54 UTC, veschii0nevstrui commented on tasks/01-Calculator.md
> -
Не знаю. Намеренно я этого точно не делал. Как его вернуть - не знаю

2016-10-17 14:02 UTC, malchun commented on tasks/01-Calculator.md
> -
Предлагаю с этим разобраться. Гит имеет все необходимые инструменты для этого. Проверить получилось или нет - можно на странице https://github.com/fediq/mipt-java-2016/pull/105/files. По конкретным нюансам работы гита - в официальное руководство и ко мне. У вас есть время до 12.

2016-10-17 19:42 UTC, malchun commented on tasks/01-Calculator.md
> +
Сойдет за решение. Но я бы на вашем месте все-таки разобрался, кто вместо вас удаляет файлы, не относящиеся к вашему проекту.

2016-10-17 19:44 UTC, malchun approved these changes

2016-10-17 19:44 UTC, merged