Task 2.
fediq/mipt-java-2016 pull request #138
Opened 2016-10-29 21:03 UTC by codelovin

2016-11-02 22:47 UTC, malchun requested changes
В целом норм, но править общие тесты не следует.

2016-11-02 22:47 UTC, malchun commented on homework-g595-shakhray/src/main/java/ru/mipt/java2016/homework/g595/shakhray/task2/FileLocking/FileLocker.java
> +
А почему не final?

2016-11-02 22:47 UTC, malchun commented on homework-tests/src/main/java/ru/mipt/java2016/homework/tests/task2/AbstractSingleFileStorageTest.java
>              storage.write("foo", "bar");
А зачем вы удалили тесты?

2016-11-05 04:02 UTC, malchun reviewed
Не ставлю блокер, т. к. это не влияет на 2е задание.

2016-11-05 04:02 UTC, malchun commented on homework-g595-shakhray/src/main/java/ru/mipt/java2016/homework/g595/shakhray/task2/FileLocker/FileLocker.java
> +        }
Замечание про необходимость критической секции было дано не просто так. В данном виде локер не то чтобы работает.

2016-11-05 04:04 UTC, codelovin commented on homework-g595-shakhray/src/main/java/ru/mipt/java2016/homework/g595/shakhray/task2/FileLocker/FileLocker.java
> +        }
Ну, протестировано это никак не было. А почему не работает? Можно в классе объявлять

2016-11-08 22:14 UTC, merged