g595.gusarova.task2
fediq/mipt-java-2016 pull request #160
Opened 2016-10-30 23:46 UTC by DariaGusarova

2016-11-08 23:08 UTC, malchun requested changes
Пожалуйста, поправьте недочеты до субботы.

2016-11-08 23:08 UTC, malchun commented on homework-g595-gusarova/pom.xml
> +        </dependency>
Ваш пом все ещё содержит абсолютно не нужный вам jeval и дважды импортит тесты. Нехорошо.

2016-11-08 23:08 UTC, malchun commented on homework-g595-gusarova/src/main/java/ru/mipt/java2016/homework/g595/gusarova/task2/KVStorage.java
> +        f = new File(path + "/storage.txt");
Используйте File.separator вместо "/".

2016-11-08 23:08 UTC, malchun commented on homework-g595-gusarova/src/main/java/ru/mipt/java2016/homework/g595/gusarova/task2/KVStorage.java
> +            dateInMap = false;
Этот флаг сбивает с толку своим названием.

2016-11-08 23:08 UTC, malchun commented on homework-g595-gusarova/src/main/java/ru/mipt/java2016/homework/g595/gusarova/task2/KVStorage.java
> +            return map.get(key);
HashMap прекрасно умеет это сам.

2016-11-08 23:08 UTC, malchun commented on homework-g595-gusarova/src/main/java/ru/mipt/java2016/homework/g595/gusarova/task2/KVStorage.java
> +            map.put(key, value);
И это HashMap тоже умеет.

2016-11-09 17:12 UTC, DariaGusarova commented
поправила

2016-11-20 22:51 UTC, DariaGusarova commented
добавила третье задание

2016-12-15 19:21 UTC, malchun reviewed
Было бы все-таки неплохо реализовать валидацию через хэш... ну да ладно. Готовьтесь к вопросу о потокобезопасности вашего хранилища. Замержу после исправления недочетов.

2016-12-15 19:21 UTC, malchun commented on homework-g595-gusarova/pom.xml
>              <version>1.0.0</version>
Верните scope пожалуйста.

2016-12-15 19:21 UTC, malchun commented on homework-g595-gusarova/src/main/java/ru/mipt/java2016/homework/g595/gusarova/task2/KVStorage.java
> +    public void close() throws IOException {
close() по описанию должен выбрасывать только IOException и только если используемые ресурсы не удается освободить. Если база закрыта - не нужно ничего делать.

2016-12-15 19:21 UTC, malchun commented on homework-g595-gusarova/pom.xml
> -            <scope>test</scope>
Верните scope.

2016-12-17 00:26 UTC, malchun commented on homework-g595-gusarova/pom.xml
> +        </dependency>
таким образом scope вы не вернули. Зато тесты импортятся аж три раза. С запасом.

2016-12-17 12:29 UTC, merged