homework-g595-kryloff-second_task
fediq/mipt-java-2016 pull request #177
Opened 2016-10-31 17:08 UTC by kryloffgregory

2016-11-08 23:12 UTC, malchun requested changes
Исправьте недочеты до субботы.

2016-11-08 23:12 UTC, malchun commented on homework-g595-kryloff/pom.xml
> +            <version>${project.version}</version>
А с какой целью здесь два импорта тестов? И да, к следущему заданию не забудьте вернуть scope.

2016-11-08 23:12 UTC, malchun commented on homework-g595-kryloff/src/main/java/ru/mipt/java2016/homework/g595/kryloff/task2/JMyKVStorage.java
> +        }
Здесь можно и нужно переписать в один if без использования флагов.

2016-11-08 23:12 UTC, malchun commented on pom.xml
> +
Выглядит как потенциальная проблема для остальных мерджей. Приведите в соответствие с общим помом пожалуйста.

2016-11-10 01:28 UTC, kryloffgregory commented
Исправил.

>Среда,  9 ноября 2016, 2:12 +03:00 от malchun <notifications@github.com>:
>
>@malchun requested changes on this pull request.
>Исправьте недочеты до субботы.
>----------------------------------------------------------------------
>In  homework-g595-kryloff/pom.xml :
>> @@ -24,7 +24,13 @@
             <groupId>ru.mipt.java2016</groupId>
             <artifactId>homework-tests</artifactId>
             <version>1.0.0</version>
-            <scope>test</scope>
+            <!--<scope>test</scope> -->
+        </dependency>
+        
+        <dependency>
+            <groupId>${project.groupId}</groupId>
+            <artifactId>homework-tests</artifactId>
+            <version>${project.version}</version>
>А с какой целью здесь два импорта тестов? И да, к следущему заданию не забудьте вернуть scope.
>----------------------------------------------------------------------
>In  homework-g595-kryloff/src/main/java/ru/mipt/java2016/homework/g595/kryloff/task2/JMyKVStorage.java :
>> +            try {
+                file.createNewFile();
+            } catch (IOException e) {
+                throw new RuntimeException("Cannot create file");
+            }
+            justCreated = true;
+        }
+        storageMap = new HashMap<>();
+        try {
+            storage = new RandomAccessFile(file.getName(), "rw");
+        } catch (IOException e) {
+            throw new RuntimeException("Cannot create random access file");
+        }
+        if (!justCreated) {
+            getData();
+        }
>Здесь можно и нужно переписать в один if без использования флагов.
>----------------------------------------------------------------------
>In  pom.xml :
>> @@ -85,8 +86,8 @@
         <module>homework-g597-miller</module>
         <module>homework-g597-smirnova</module>
         <module>homework-g596-grebenshchikova</module>
-        <module>homework-g597-kochukov</module>
-        <module>workshop-materials</module>
+        <module>homework-g597-kochukov</module> 
+        
>Выглядит как потенциальная проблема для остальных мерджей. Приведите в соответствие с общим помом пожалуйста.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-11-15 15:02 UTC, malchun commented on homework-g595-kryloff/.LCKpom.xml~
> +/home/krylof/Programming/mipt-java-2016/homework-g595-kryloff/pom.xml
Есть мнение, что это что-то лишнее в вашем проекте.

2016-11-15 15:04 UTC, malchun reviewed
Ваш PR не только добавляет бинарник Софьи, но притаскивает ещё и свой. Кажется вы сохраняете базу куда-то не туда.

2016-11-16 07:45 UTC, malchun requested changes

2016-11-16 07:45 UTC, malchun commented on homework-g595-kryloff/pom.xml
> +            <!--<scope>test</scope> -->
?

2016-11-16 22:12 UTC, merged