g594.nevstruev.task2
fediq/mipt-java-2016 pull request #184
Opened 2016-10-31 19:28 UTC by veschii0nevstrui

Решение второго задания

2016-11-15 14:43 UTC, malchun requested changes

2016-11-15 14:43 UTC, malchun commented on homework-g594-nevstruev/pom.xml
> +        </dependency>
Зачем два импорта? Сделай уже один и со scope

2016-11-15 15:31 UTC, veschii0nevstrui commented on homework-g594-nevstruev/pom.xml
> +        </dependency>
А как я со scope это сделаю? Я ведь в main пользуюсь Student

2016-11-15 17:34 UTC, veschii0nevstrui commented on homework-g594-nevstruev/pom.xml
> +        </dependency>
Я ничего не понял. 
Со scope у меня всё работает и компилируется, а тут не хочет

2016-11-16 16:43 UTC, malchun requested changes

2016-11-16 16:43 UTC, malchun commented on homework-g594-nevstruev/pom.xml
> -            <scope>test</scope>
Почему то я помню задание "добавить scope", но не помню задания "убрать scope"

2016-11-16 18:22 UTC, veschii0nevstrui commented on homework-g594-nevstruev/pom.xml
> -            <scope>test</scope>
Если добавить scope test, то код перестанет компилироваться у меня, по вполне понятным причинам - я в main пользуюсь классом Student, который как аз лежит в homework-test. 

Если же добавить scope main, то код у меня локально начнёт работать нормально - что и ожидается от него. Но на сайте он почему-то даже не компилируется. Причём по моему пониманию(и по пониманию моего компа) он должен компилироваться. Я совсем ничего не понимаю, тем более что мне обещали, что Java везде работает одинаково.

2016-11-16 20:02 UTC, malchun commented on homework-g594-nevstruev/pom.xml
> -            <scope>test</scope>
1) как решить проблему неработающего в scope  test кода было объяснено неоднократно, и в чате, и на семинаре. Большая часть ваших одногруппников эту проблему успешно решили.
2) Если у вас локально все работает, а на сервере нет - то есть подозрение, что при билде через идею вы забыли заимпортить изменения в pom.xml, коим и является добавление scope. Проверьте, не предлагает ли вам идея сделать это в правом ниженм углу.

2016-11-16 20:29 UTC, veschii0nevstrui commented on homework-g594-nevstruev/pom.xml
> -            <scope>test</scope>
Я всё импортил

2016-11-25 15:29 UTC, merged