Group-594_Petrov_Filipp_Task1
fediq/mipt-java-2016 pull request #22
Opened 2016-10-10 20:17 UTC by yaPhilya

Calculator

2016-10-11 23:11 UTC, malchun requested changes
Проект не собирается из-за отсутствующих зависимостей.

2016-10-11 23:11 UTC, malchun commented on homework-g594-petrov/pom.xml
> +    <artifactId>homework-g594-petrov</artifactId>
Вы забыли зависимости. Без них проект не собирается. Если у вас этой проблемы нет - значит в вашем случае зависимости подтягивает IDE. Т. к. конфигурационные файлы вашей IDE мне недоступны - прошу добавить зависимости через maven. Как только задание будет собираться - оно будет проверено.

2016-10-11 23:26 UTC, yaPhilya commented on homework-g594-petrov/pom.xml
> +    <artifactId>homework-g594-petrov</artifactId>
Добавил зависимости.

2016-10-12 07:43 UTC, malchun requested changes
В целом неплохо, после исправления указанных мест будет принято на 2 балла. Отдельная благодарность от меня - если оно прекратит конфликтовать при мерже.

2016-10-12 07:43 UTC, malchun commented on homework-g594-petrov/src/main/java/ru/mipt/java2016/homework/g594/petrov/task1/MegaCalculator.java
> +                                postfixNotation.append(' ').append(operatorStack.lastElement()).append(' ');
pop() возвращает объект, который удаляет.

2016-10-12 07:43 UTC, malchun commented on homework-g594-petrov/src/main/java/ru/mipt/java2016/homework/g594/petrov/task1/MegaCalculator.java
> +import com.sun.deploy.net.proxy.pac.PACFunctions;
Эти ненужные импорты по прежнему не позволяют собрать проект.

2016-10-12 07:43 UTC, malchun commented on homework-g594-petrov/src/main/java/ru/mipt/java2016/homework/g594/petrov/task1/MegaCalculator.java
> +            if(OPERATORS.contains(c))
Это не ошибка а замечание по стилю. Такое количество if'ов балансирует на грани spaghetti code, и в таких случаях иногда имеет смысл пересмотреть логику работу программы.

2016-10-12 19:35 UTC, yaPhilya commented on homework-g594-petrov/src/main/java/ru/mipt/java2016/homework/g594/petrov/task1/MegaCalculator.java
> +import com.sun.deploy.net.proxy.pac.PACFunctions;
Убрал

2016-10-12 19:35 UTC, yaPhilya commented on homework-g594-petrov/src/main/java/ru/mipt/java2016/homework/g594/petrov/task1/MegaCalculator.java
> +                                postfixNotation.append(' ').append(operatorStack.lastElement()).append(' ');
Заменил

2016-10-14 05:46 UTC, merged