Add calculator implementation
fediq/mipt-java-2016 pull request #26
Opened 2016-10-11 01:19 UTC by lajulienn

2016-10-11 13:20 UTC, DanAnastasyev requested changes
Нужно поправить ещё кодстайл. Скачай плагин checkStyle и поменяй все названия переменных, на которые он будет ругаться, добавь скобки вокруг однострочных ифов и укороти слишком длинные строки
Еще нужно поменять порядок расположения public/private полей и методов
Code conventions можно посмотреть здесь: http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +    private class Token {
Лучше сделать abstract

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                number += symbol;
Строки в java иммутабельны, поэтому при конкатенации создаются новые строки. Лучше работать со StringBuilder. У него определен метод append, а получить строку из него можно с помощью ToString().

А ещё лучше - сразу собирать полное значение: читать посимвольно, пока не встретится оператор, превращать в значение. Заодно проверка на лишнюю точку красивее будет

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                        symbol = '!';
Два очень сложных и некрасивых ифа подряд.
Стоит хотя бы выделить условия в них в пару методов с говорящими названиями.
В стиле `if (symbol == '-' && isUnaryMinusAllowed(previous)) {...}`

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +        throw new ParsingException("Invalid expression.");
Вот такие вещи точно стоит комментировать. Почему `return` именно такой и зачем бросать исключение в противном случае

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +    private boolean isOperator(char symbol) {
В метод передается экземпляр Character, а принимается char - значит, случается [unboxing](https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html), а это не круто (лишние операции).

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +            expression.remove(0);
`remove `возвращает значение - можно было бы сэкономить строчку.

А вообще `ArrayList `- это аналог вектора в C++. Не очень хорошо удалять из массива первый элемент и сдвигать его. Кажется, вполне можно было бы его на `LinkedList `- аналог списка в C++. Тогда операции тут будут дешевле, а код доступа к последнему элементу в `tokenize` - изящнее (не `tokenized_expr.get(tokenized_expr.size() - 1)`, а просто 'getLast()').

2016-10-11 13:20 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +    private ArrayList<Token> tokenize(String expression) throws ParsingException {
Почитай про [Scanner](http://www.geeksforgeeks.org/scanner-class-in-java/). С ним можно было бы реализовать эту функцию проще. Хотя, конечно, можно и так пока оставить

2016-10-11 14:36 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +    private class Token {
Done.

2016-10-11 17:13 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +    private boolean isOperator(char symbol) {
Исправила на isOperator(Character symbol)

2016-10-11 17:24 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +            expression.remove(0);
Done.

2016-10-11 19:37 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                        symbol = '!';
Done.

2016-10-11 19:38 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +        throw new ParsingException("Invalid expression.");
Done.

2016-10-11 20:14 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                number += symbol;
Done.

2016-10-11 20:21 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +    private boolean isOperator(char symbol) {
А нет, переписала без оберток, они же не нужны.

2016-10-12 19:54 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                char next;
Можно было бы прямо в цикле переменную объявлять. Незачем расширять область видимости. По скорости это ничего не даст

2016-10-12 19:54 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                    if (symbol == '-' && isUnaryMinus(previous, new Operator(symbol))) {
`isUnaryMinus` же даже не использует второй аргумент. Создавать его по new зазря - жестоко как-то

2016-10-12 19:54 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                    if ((previous instanceof Operator) && !(symbol == '!')) {
`symbol != '!'` же можно :)

2016-10-12 19:54 UTC, DanAnastasyev commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                number = new StringBuilder();
Вот это лишнее тут.
Для скорости можно действительно держать один экземпляр `StringBuilder` и чистить его с помощью `delete`. Так быстрее, говорят

2016-10-12 21:10 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                char next;
Done.

2016-10-12 21:13 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                    if (symbol == '-' && isUnaryMinus(previous, new Operator(symbol))) {
Fixed.

2016-10-12 21:15 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                    if ((previous instanceof Operator) && !(symbol == '!')) {
Правильно, он может идти после оператора, поэтому мы бросаем исключение на случаи, когда 2 оператора подряд и второй не унарный минус.

2016-10-12 21:16 UTC, lajulienn commented on homework-g596-ivanova/src/main/java/ru/mipt/java2016/homework/g596/ivanova/task1/BestCalculatorEver.java
> +                number = new StringBuilder();
Done.

2016-10-12 21:55 UTC, DanAnastasyev approved these changes

2016-10-12 21:55 UTC, merged