g594-stepanov-task1
fediq/mipt-java-2016 pull request #36
Opened 2016-10-11 20:56 UTC by irkstepanov

2016-10-15 08:03 UTC, malchun requested changes
Поправьте зависимости проекта и поправьте кодстайл.

2016-10-15 08:03 UTC, malchun commented on homework-g594-stepanov/CalculatorImplementation.java
> +
Этот файл в репозитории лишний.

2016-10-15 08:03 UTC, malchun commented on homework-g594-stepanov/pom.xml
> +        </dependency>
Вы сотворили трэш и угар с зависимостями. Поправьте.

2016-10-15 08:03 UTC, malchun commented on homework-g594-stepanov/src/main/java/ru/mipt/java2016/homework/g594/stepanov/task1/CalculatorImplementation.java
> +            }
String.replaceAll и \s делают это в одну строчку.

2016-10-15 08:03 UTC, malchun commented on homework-g594-stepanov/src/main/java/ru/mipt/java2016/homework/g594/stepanov/task1/CalculatorImplementation.java
> +    private double f(int lf, int rg) throws ParsingException {
Не думаю что это пройдет проверку кодстайла.

2016-10-15 15:23 UTC, irkstepanov commented on homework-g594-stepanov/pom.xml
> +        </dependency>
Кажется, всё поправил.

2016-10-16 10:57 UTC, malchun approved these changes

2016-10-16 10:57 UTC, malchun commented on homework-g594-stepanov/pom.xml
> +        </dependency>
Эта зависимость тоже явно лишняя, единственное для чего она нужна - неиспользуемый импорт в тесте.

2016-10-16 10:57 UTC, malchun commented on homework-g594-stepanov/src/test/java/ru/mipt/java2016/homework/g594/stepanov/task1/CalculatorTestImplementation.java
> +import ru.mipt.java2016.homework.g000.lavrentyev.task1.CachedJEvalCalculator;
Вот этот неиспользуемый импорт.

2016-10-16 11:02 UTC, malchun requested changes
Дофиксите зависимости.

2016-10-16 20:08 UTC, merged